name: NASA Project CI
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js version 20
        uses: actions/setup-node@v6
        with:
          node-version: '20'
      - name: Enable Corepack (pnpm)
        run: corepack enable
      - name: Install dependencies
        run: pnpm run install
      - name: Build client
        run: pnpm --prefix client run build
        env:
          CI: false